# Utiliser l'image officielle de Node.js version 20.14.0 comme base
FROM node:20.14.0

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le code source de l'application dans le conteneur
COPY . .

# Installer les dépendances0
RUN npm ci

# Construire l'application Next.js
RUN npm run build

# Exposer le port 3000
EXPOSE 3000

# Démarrer l'application
CMD ["npm", "start"]