version: '3.8'

services:
    gest_bibli:
        container_name: gest-bibli
        restart: always
        build:
            context: .
            dockerfile: dockerFile
        # ports:
        #     - 8083:3000
        networks:
            - internal
            - web
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.gestbibli.rule=Host(`gest-bibli.projets-al.site`)'
            - 'traefik.http.routers.gestbibli.entrypoints=websecure'
            - 'traefik.http.services.gestbibli.loadbalancer.server.port=3000'
            - 'traefik.http.routers.gestbibli.tls.certresolver=myresolver'
            - 'traefik.docker.network=web'

networks:
    web:
        external:
            name: web
    internal:
