import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import Logo from '@/assets/logo.png';
import ToastProvider from "@/contexts/ToastContext";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Gest_bibli",
  description: "Generated by create next app",
  icons:{
    icon : Logo.src,
  }
};


export const viewport: Viewport = {
	initialScale: 1,
	userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ToastProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F6F9FE] h-[100svh]`}
        >
        {children}
      </body>
          </ToastProvider>
        </AuthProvider>
    </html>
  );
}
